47.49980447.227952
x1>x2
length of points array is 65
Traceback (most recent call last):
  File "/users/tlezuo/icon-vis/vertical_cross_sections/vcs_plot_loop.py", line 405, in <module>
    VCS = get_vcs(line,pdate)
  File "/users/tlezuo/icon-vis/vertical_cross_sections/vcs_plot_loop.py", line 314, in get_vcs
    regrid_CTRL_U = cross_section(A, B, Step, 'TRUE', icon_gp_file,clon_CTRL,clat_CTRL,
  File "/users/tlezuo/icon-vis/vertical_cross_sections/vcs_plot_loop.py", line 185, in cross_section
    ter = griddata(points_icon_coords, zz, coords_in_line, method=interp_meth)    
  File "/scratch/tlezuo/miniconda3/envs/psyplot/lib/python3.9/site-packages/scipy/interpolate/_ndgriddata.py", line 264, in griddata
    ip = CloughTocher2DInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 908, in scipy.interpolate.interpnd.CloughTocher2DInterpolator.__init__
  File "_qhull.pyx", line 1846, in scipy.spatial._qhull.Delaunay.__init__
  File "_qhull.pyx", line 358, in scipy.spatial._qhull._Qhull.__init__
scipy.spatial._qhull.QhullError: QH6014 qhull internal error (qh_maxsimplex): not enough points available

While executing:  | qhull d Qt Qc Q12 Qz Qbb
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 281566586  delaunay  Qtriangulate  Qcoplanar-keep  Q12-allow-wide
  Qz-infinity-point  Qbbound-last  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width 2.6e+179  Error-roundoff 3.6e+164  _one-merge 2.5e+165
  Visible-distance 7.3e+164  U-max-coplanar 7.3e+164  Width-outside 1.5e+165
  _wide-facet 4.4e+165  _maxoutside 2.9e+165

A Qhull internal error has occurred.  Please send the input and output to
qhull_bug@qhull.org. If you can duplicate the error with logging ('T4z'), please
include the log file.

